# Generated by Django 2.2.24 on 2021-10-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '7128_resource_instance_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='alias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
